{
 "title": "PBFT Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "source",
    "query": {
     "query": "label_values(message_count,from)"
    }
   },
   { "name": "destination", "query": { "query": "label_values(message_count,to)" } },
   { "name": "quantile", "query": "0.5,0.9,0.95,0.99" }
  ]
 },
 "panels": [
  {
   "title": "Last Executed Request",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(executed_requests) by (node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Leaders",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(leader_counter[$__interval])) by (node_id, leader_id) > 0",
     "legendFormat": "{{leader_id}} leads {{node_id}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(error_count[$__interval])) by (component, step, error)",
     "legendFormat": "{{component}}::{{step}} {{error}}"
    }
   ]
  },
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Message Count ($source -> $destination)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(irate(message_count{from=~\"$source\",to=~\"$destination\"}[$__interval])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Last Executed Request Drift",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($B - $A)", "type": "math" }
   ]
  },
  {
   "title": "Response Time ($source)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(node_response_time{node=~\"$source\",quantile=\"$quantile\"}) by (action)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(client_request_status{}[$__interval])) by (status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Execution Latency ($source) [$quantile quantile]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(client_request_latency{node=~\"$source\",quantile=\"$quantile\"}) by (node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Message Status Error ($source -> $destination)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(message_status{from=~\"$source\", to=~\"$destination\", status!=\"success\"}[$__interval])) by (action, status)",
     "legendFormat": "{{action}} -- {{status}}"
    }
   ]
  },
  {
   "title": "In Progress Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(in_progress_requests{}) by (node)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Load Test", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Sent Request",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum(irate(load_test_request_count{}[$__interval])) by (status)",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}